name: Publish

on:
 push:
   branches: [main, develop]

jobs:
  publish:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            args: --linux
          - os: windows-latest
            args: --win
#          - os: macos-latest
#            args: --mac
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - if: matrix.os == 'macos-latest'
        name: Install macOS dependencies
        run: npm install dmg-license

      - name: Install dependencies
        run: npm install

      - name: Build & Publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run postinstall
          npm run build
          npm exec electron-builder -- --publish always ${{ matrix.args }}
