name: Publish

on:
 push:
   branches: [main, develop]

jobs:
  publish:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            args: --linux
          - os: windows-latest
            args: --win
          - os: macos-latest
            args: --mac
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 20
    # Platform specific install
      - if: matrix.os == 'ubuntu-latest'
        name: Linux Install
        run: |
          npm install --ignore-scripts
          npm install electron-builder app-builder-lib --save-dev

      - if: matrix.os != 'ubuntu-latest'
        name: Other OS Install
        run: npm install

      - name: Build & Publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm run postinstall
          npm run build
          npm exec electron-builder -- --publish always ${{ matrix.args }}

